apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-db
  template:
    metadata:
      labels:
        app: booking-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: booking_service
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: booking-db
spec:
  selector:
    app: booking-db
  ports:
    - port: 3306
      targetPort: 3306
